import os
import json
import asyncio
from pathlib import Path
from PIL import Image
from rembg import remove
from pydantic import BaseModel, Field
from typing import List, Optional
from PIL import Image, ImageFilter

from dotenv import load_dotenv
load_dotenv()

from schemas import MarketingSEOOutput, CriticOutput, FinalListingOutput

from aiogram import Bot, Dispatcher, F
from aiogram.types import Message

from crewai import Agent, Crew, Process, Task, LLM

from etsy_api import EtsyAPIClient

os.environ["GEMINI_API_KEY"] = os.getenv("GEMINI_API_KEY")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

os.environ["ETSY_CLIENT_ID"] = os.getenv("ETSY_CLIENT_ID")
os.environ["ETSY_SHARED_SECRET"] = os.getenv("ETSY_SHARED_SECRET")
ETSY_SHOP_ID = os.getenv("ETSY_SHOP_ID")

llm_model = LLM(
    model="gemini/gemini-2.5-flash",
    temperature=0.4,
    api_key=os.environ["GEMINI_API_KEY"]
)

bot = Bot(token=TELEGRAM_BOT_TOKEN)
dp = Dispatcher()

MEDIA_DIR = Path("media")
MEDIA_DIR.mkdir(exist_ok=True)

def process_multiple_images() -> dict:
    print("\n📸 [Photo Editor] Processing all images in media folder with Pro FX...")
    result = {"photo_processed": False, "all_photos": [], "video_found": False, "video_path": None}
    
    photo_files = sorted(list(MEDIA_DIR.glob("product_*.jpg")))
    
    if photo_files:
        main_image_path = photo_files[0]
        
        print(f"✂️ Removing background and applying soft shadow to main photo: {main_image_path.name}...")
        try:
            input_image = Image.open(main_image_path)
            
            image_no_bg = remove(input_image)
            
            r, g, b, alpha = image_no_bg.split()
            
            feathered_alpha = alpha.filter(ImageFilter.GaussianBlur(radius=1.5))
            image_feathered = Image.merge("RGBA", (r, g, b, feathered_alpha))
            
            max_side = max(image_no_bg.size)
            shadow_blur_radius = max_side // 50
            
            shadow_mask = alpha.filter(ImageFilter.GaussianBlur(radius=shadow_blur_radius))
            
            shadow_mask = shadow_mask.point(lambda p: int(p * 0.35))
            
            shadow_color = (55, 45, 45) 
            shadow_layer = Image.new("RGBA", image_no_bg.size, shadow_color)
            
            pastel_pink_color = (255, 240, 245)
            background = Image.new("RGB", image_no_bg.size, pastel_pink_color)
            
            offset_x = max_side // 65
            offset_y = max_side // 45
            
            background.paste(shadow_layer, (offset_x, offset_y), mask=shadow_mask)
            background.paste(image_feathered, (0, 0), mask=image_feathered)
            
            output_image_path = MEDIA_DIR / "product_1_pink_bg.jpg"
            background.save(output_image_path, "JPEG", quality=95)
            
            result["photo_processed"] = True
            result["all_photos"].append(str(output_image_path))
            
        except Exception as e:
            print(f"⚠️ Could not process background for main photo: {e}")
            result["all_photos"].append(str(main_image_path))
        
        for extra_photo in photo_files[1:]:
            result["all_photos"].append(str(extra_photo))
            
        print(f"✅ Photos preparation finished. Total photos ready: {len(result['all_photos'])}")
    else:
        print("❌ Warning: No photos found to process.")
        
    video_path = MEDIA_DIR / "product.mp4"
    if video_path.exists():
        result["video_found"] = True
        result["video_path"] = str(video_path)
        
    return result

#CREWAI WORKFLOW FUNCTION
def run_ai_workflow(product_description: str, media_report: dict) -> str:
    
    main_photo_path = None
    if media_report.get("all_photos") and len(media_report["all_photos"]) > 0:
        main_photo_path = media_report["all_photos"][0]

    photo_editor_agent = Agent(
        role='Etsy Media Manager',
        goal='Oversee media asset readiness and confirm paths for Etsy upload.',
        backstory='You ensure all visual assets are correctly prepared.',
        verbose=True,
        llm=llm_model
    )

    seo_specialist = Agent(
        role='Etsy SEO Specialist and Product Analyst',
        goal='Analyze product images and user notes to generate rich, high-converting Etsy listing assets.',
        backstory='You have a sharp eye for visual details. You examine the provided product photo, identify its material, style, color, and unique features, combine this with the user\'s brief, and build a master SEO strategy.',
        verbose=True,
        llm=llm_model,
        max_iter=3
    )

    seo_critic = Agent(
        role='Etsy Quality and Policy Auditor',
        goal='Critique, validate, and correct the metadata generated by the SEO specialist.',
        backstory='You are an unforgiving Etsy auditor. You ensure tags strictly don\'t exceed 20 characters, duplicate tags are deleted, and no prohibited trademark words are used.',
        verbose=True,
        llm=llm_model,
        max_iter=3
    )

    final_refiner = Agent(
        role='Etsy Shop Copywriter',
        goal='Assemble the final, polished Etsy listing package using an authentic, artisan first-person voice.',
        backstory=(
            "You are a passionate independent artist selling your own handmade creations on Etsy. "
            "You strictly write in the singular first-person ('I', 'me', 'my') or completely neutral voice. "
            "You NEVER use corporate or plural marketing pronouns like 'we', 'our', 'us', or 'Discover our...'. "
            "Your tone is warm, personal, honest, and creative—like a maker talking directly to a friend. "
            "Avoid generic marketing clichés and focus on the story, craftsmanship, and soul of the item."
        ),
        verbose=True,
        llm=llm_model
    )

    # TASKS
    task_media = Task(
        description=f"Verify the processed media results. Current assets report: {json.dumps(media_report)}. Confirm if images and videos are ready for deployment.",
        expected_output="A confirmation string specifying the available media paths.",
        agent=photo_editor_agent
    )

    task_research = Task(
        description=(
            "1. Carefully examine the attached product image.\n"
            f"2. Read the user's provided context for this item: '{product_description}'.\n"
            "3. Generate a highly detailed internal analysis of what you see on the image (style, texture, aesthetics) combining it with the user's context.\n"
            "4. Based on this visual and textual research, create an optimized Etsy title (STRICTLY UNDER 120 characters to avoid system rejection (safe margin)), exactly 13 tags, and a comprehensive description that highlights the visual features of the item.\n"
            "5. CRITICAL RULE FOR TAXONOMY ID: Analyze the product type and choose the exact taxonomy_id for the JSON output:\n"
            "   - If it is a keychain (брелок), set \"taxonomy_id\": 165\n"
            "   - If it is a necklace or pendant (підвіска/намисто), set \"taxonomy_id\": 1217\n"
            "   - If it is earrings (сережки), set \"taxonomy_id\": 6764\n"
            "   Do not use any other numbers for taxonomy_id."
        ),
        expected_output="A JSON object containing the title, tags, description, and the correct taxonomy_id based on product type.",
        output_json=MarketingSEOOutput,
        agent=seo_specialist,
        images=[main_photo_path] if main_photo_path else []
    )
    task_review = Task(
        description="Review the JSON output from the SEO Specialist. Ensure all 13 tags are strictly under 20 characters and highly accurate. Provide corrections if necessary.",
        expected_output="A JSON object containing approval status, constructive feedback, and the corrected tags list.",
        output_json=CriticOutput,
        agent=seo_critic
    )

    task_finalize = Task(
        description=(
            "Combine the verified text and the media assets from the report. "
            "Generate the absolute final, ready-to-upload draft data package. "
            "CRITICAL WRITING RULES FOR DESCRIPTION:\n"
            "1. NEVER use the words 'our', 'we', 'us' or corporate clichés like 'Discover our exquisite...'.\n"
            "2. Write from the perspective of a solo artist ('I handcrafted this...', 'My polymer clay pieces...').\n"
            "3. Focus on real details: what it feels like, how it looks on a bag, and the effort put into making it.\n"
            "4. Keep sentences clean, natural, and highly readable, formatted with line breaks."
        ),
        expected_output="The final compiled JSON listing package containing title, tags, description written in an authentic artisan voice.",
        output_json=FinalListingOutput,
        agent=final_refiner
    )

    crew = Crew(
        agents=[photo_editor_agent, seo_specialist, seo_critic, final_refiner],
        tasks=[task_media, task_research, task_review, task_finalize],
        process=Process.sequential
    )
    
    output = crew.kickoff()
    return output.raw

# 5. TELEGRAM BOT HANDLERS & SECURITY
ALLOWED_USERS = json.loads(os.getenv("ALLOWED_USERS_ID", "[]"))

photo_counter = 0

@dp.message(F.text == "/start")
async def cmd_start(message: Message):
    if message.from_user.id not in ALLOWED_USERS:
        await message.answer("⛔️ Access denied. This bot is a private tool.")
        return

    await message.answer(
        "👋 Hello! I am your Etsy AI Assistant.\n\n"
        "Send me your product photos as an album and make sure to include the product description in the caption!"
    )

@dp.message(F.photo)
async def handle_photo(message: Message):
    if message.from_user.id not in ALLOWED_USERS:
        await message.answer("⛔️ Access denied. This bot is a private tool.")
        return

    global photo_counter
    
    if photo_counter == 0:
        for item in MEDIA_DIR.glob("*"):
            if item.is_file():
                try:
                    item.unlink()
                except PermissionError:
                    pass
                
    photo_counter += 1
    photo = message.photo[-1]
    
    photo_path = MEDIA_DIR / f"product_{photo_counter}.jpg"
    await bot.download(photo, destination=photo_path)
    
    if message.caption:
        product_desc = message.caption
        current_photos_count = photo_counter
        photo_counter = 0
        
        await message.answer(f"📥 Photos uploaded: {current_photos_count}. Processing media...")
        await asyncio.sleep(2)
        
        loop = asyncio.get_event_loop()
        media_report = await loop.run_in_executor(None, process_multiple_images)
        
        await message.answer("🧠 Media files are ready. Initiating CrewAI agent team...")
        ai_result = await loop.run_in_executor(None, run_ai_workflow, product_desc, media_report)

        await message.answer("📦 Text generated. Initiating Etsy API integration...")
        try:
            listing_data = json.loads(ai_result)
            etsy_client = EtsyAPIClient(shop_id=ETSY_SHOP_ID)
            etsy_client.get_and_save_taxonomy()
        
            # Step 1: Create the draft (Title, Description, Category, Tags — ALL IN ONE)
            await message.answer("📝 Step 1/2: Creating draft listing with SEO tags and materials...")
        
            ai_title = listing_data.get("title", "")
            if len(ai_title) > 140:
                ai_title = ai_title[:140]
            
            ai_description = listing_data.get("description")
            ai_tags = listing_data.get("tags", [])
            ai_taxonomy = listing_data.get("taxonomy_id") if listing_data.get("taxonomy_id") else 1326

            listing_id = await loop.run_in_executor(
                None,
                lambda: etsy_client.create_draft_listing(
                    title=ai_title,
                    description=ai_description,
                    tags=ai_tags,       
                    price=15.0,
                    quantity=1,
                    taxonomy_id=int(ai_taxonomy)
                )
            )

            # Step 2: Loop through and upload all images
            if media_report and media_report.get("all_photos"):
                total_photos = len(media_report["all_photos"])
                await message.answer(f"📸 Step 2/2: Starting media files upload (Total: {total_photos})...")
            
                for index, photo_file_path in enumerate(media_report["all_photos"], start=1):
                    status_msg = "primary image (with pastel background)" if index == 1 else f"additional image #{index-1}"
                    await message.answer(f"⏳ Uploading {status_msg}...")
                
                    await loop.run_in_executor(
                        None,
                        etsy_client.upload_listing_image,
                        listing_id,
                        photo_file_path,
                        index
                    )
        
            await message.answer(
                f"🎉 **Success! Listing completely exported.**\n\n"
                f"🔹 **Listing ID:** `{listing_id}`\n"
                f"🔹 **Status:** Draft\n\n"
                f"Check your Etsy Shop Manager!"
            )
        
        except Exception as api_error:
            print(f"Etsy API Error: {api_error}")
        
            await message.answer(
                f"⚠️ Failed to export data to Etsy.\n"
                f"Error: {str(api_error)}\n\n"
                f"Here is the AI-generated text, you can copy it manually:\n\n"
                f"{ai_result}"
            )

@dp.message(F.video)
async def handle_video(message: Message):
    if message.from_user.id not in ALLOWED_USERS:
        return

    video_path = MEDIA_DIR / "product.mp4"
    await bot.download(message.video, destination=video_path)
    await message.answer("✅ Video uploaded successfully. Now send your photos along with a description.")


async def main():
    print("🤖 Telegram Bot with CrewAI agents is running...")
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())